### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by Lensrub** [David-JonesDVN/Touhou-Relauncher#1]
Hello, I would like to offer a translation of "touhou-relauncher" into Russian. I attached a link to the translated files "MainForm.resx" and "Resources.resx" [https://www.dropbox.com/s/l90egdd92k7xbck/ru.rar?dl=0](url) And I found that the "launcherSettings", "randomSettings", "randomLabel" and "np2Label" elements are not translated, ignoring the values in "Resources.resx".

**Comment by David-JonesDVN** [comment]
Hi, thanks for taking interest in this project. I think the problems should be fixed in the 1.0 pre-release version. Along with the fixes there are also some new/modified lines so if you don't mind I'll attach the new resource file here.
[Resources_en.zip](https://github.com/David-JonesDVN/Touhou-Relauncher/files/2912589/Resources_en.zip)
Please let me know if the problems are solved or if there are any new ones.

**Comment by Lensrub** [comment]
It is necessary to slightly increase the width of the "random All" button for the translation fit.
[Resources_ru.zip](https://github.com/David-JonesDVN/Touhou-Relauncher/files/2915404/Resources_ru.zip)
And if select "thcrap" in the "Default Executable:" program has be crash

**Comment by David-JonesDVN** [comment]
Thanks for the report! I've fixed the crash and expanded the buttons in the new release (same version since it's still a pre-release).
If you think the translation is finished let me know and I'll add it to the main program.

**Comment by Lensrub** [comment]
Basically, the translation is complete. Only 3 items in the tray context menu were not translated. "Random Game" "Open" and "Exit" (They are not in "Resources.resx")

**Comment by David-JonesDVN** [comment]
Added those as "trayRandom", "trayOpen" and "trayExit".
No release/commit for now since there's no other change, but if it's done, I'll add it and release a build tomorrow with Russian language support.
Thanks for helping me find the lines I missed!

**Comment by Lensrub** [comment]
[Resources_ru2.zip](https://github.com/David-JonesDVN/Touhou-Relauncher/files/2917301/Resources_ru2.zip)
Translation with added "tray" strings.

**Comment by David-JonesDVN** [comment]
Thanks! Russian support added to the main program! I'll leave this open for some time just in case there's something wrong with the new release.
