### ISSUE TITLE
Replay websites causing errors

### ISSUE THREAD

**Issue by gabman15** [David-JonesDVN/Touhou-Relauncher#10]
Launching the program always instantly opens this error message and others like it. I believe the reason is that one of the replay websites you have included (replays.gensokyo.org) within the launcher is no longer up and you are sending requests to a dead website. This could lead to problems if someone else were to obtain that domain. I downloaded the offline version of prerelease 4 and it does the same thing. The idea of the replay website integration is good however being unable to remove the default ones is in my mind a major issue. A simple fix would be to remove the integration altogether but up to you. I can't really use the program until this is fixed so I hope you see this. Thanks for reading.
![Capture](https://user-images.githubusercontent.com/32818424/73111228-8a747480-3ed7-11ea-955e-af2e93530d9e.PNG)

**Comment by Farnker** [comment]
replays.gensokyo.org is now filled with malware and scam popups and clicking that tab in the launcher also starts generating script errors and scam popups. Pretty much renders that tab unusable and makes the launcher look sketchy.

**Comment by gabman15** [comment]
Exactly. I managed to compile the latest dev version which switched out replays.gensokyo.org to a working site which fixes it but the current release is still broke. I think there really should be a way to not depend on these websites being up to safely run the program.

**Comment by David-JonesDVN** [comment]
Ah, sorry. I was quite busy so I couldn't release a build for that fix. The latest release should now start the browser on an empty link as long as you don't press any of the buttons for replay websites. Please do comment on this page if you encounter any more issues regarding the replay websites.
