### ISSUE TITLE
Add Games on custom games tab not working

### ISSUE THREAD

**Issue by elliothawkz2** [David-JonesDVN/Touhou-Relauncher#12]
Whenever I click on the Add Games button it does absolutely nothing. I want to add MegaMari and other fangames to the mix for easy access. Any help?

**Comment by David-JonesDVN** [comment]
Hello. The custom games menu will only add games if you've added a category to the category list and have it selected (right click the empty space on the left in the custom games tab.)
For the next update I'll try adding a default category or an error that tells you why it isn't working (or even both).

**Comment by elliothawkz2** [comment]
Thank you. It's much clearer now.
