### ISSUE TITLE
Mistranslation in Japanese and some comments about the way to group the game

### ISSUE THREAD

**Issue by HoengSaan** [David-JonesDVN/Touhou-Relauncher#13]
Update: https://github.com/David-JonesDVN/Touhou-Relauncher/compare/master...HoengSaan:Touhou-Relauncher:master

Great to have this software on the computer, those shortcuts won't take up so much space as before.
Although it seems the translation is not done yet, some issues are still worth mentioning.

### First Tab: Game
![image](https://user-images.githubusercontent.com/31458520/181756369-0c6c2317-6e2a-4f93-8621-b598b3a7d0ba.png)
Different words are used to describe it in Japanese.

**「メインゲーム」**
It will better change it to 「整数作品」, it is strange just to call it "main game"
_**Comment:** I think the th01-th05 should be in another group, instead of the group with all the other Win Game. For example,  th01-th05 will be classified as 「旧作」「PC-98版」and th06-th18 will be 「本編」or「新作」or maybe「Windows版」_

**「格闘ゲーム」「他のゲーム」**
I guess calling it「格闘ゲーム」 is fine, but I will just call it 「ACT」
And the 「他のゲーム」itself literally means "other game", which may be misunderstood. It might be better translated to 「その他」or may be「その他の番外作品」(this is too long).
Both can be called 「番外編」「番外作品」「小数点作品」if grouped together.

_**Comment:** But I think you can also add the 東方剛欲異聞 to 「格闘ゲーム」 and name it as「黄昏フロンティア」or「黄昏フロンティアとの共同作品」which is the doujin circle of those games_

Random can just be「ランダム」, which is easy.

### Second Tab: Custom Games
![image](https://user-images.githubusercontent.com/31458520/181767278-8be7e6a5-75fd-430a-8951-54b6f5ca46b4.png)
"Custom Games" you may consider to translated it to 「同人ゲーム」, 
「ゲームを足す」is a weird translation, I can't understand it the first time I read. You need to change it to 「ゲームを追加する」.
**Another thing, the "New Category" is been translated to a game title「怪綺談」, which is th05.**

You can translate the three phrases to
「新規作成」
「削除」
「名前の変更」

### Fourth Tab: Settings
![image](https://user-images.githubusercontent.com/31458520/181764028-a66a39c1-ebd4-4dcc-b41b-96c38aba5612.png)
Change 「語」to「言語」will make it more natural.
you may consider change「全部」to「すべて」「全て」, or maybe 「すべて選択」
「なし」maybe is fine, but if you change it to  「すべて選択」, you should change it to 「選択解除」too.

**Comment by David-JonesDVN** [comment]
Hello. Sorry for the late answer.
Thank you for the translation notes. Most of the translation here was either done with my extremely limited knowledge, or was influenced by how the original launcher translated specific sections, so I pretty much abandoned it as a "work in progress" until I could learn how to translate it better.
About the categories, I wouldn't mind giving the PC-98 games their own, but I feel like that would result in quite a bit of wasted window space, which is why I haven't done it. Then again, if you do believe that it's for the better, you can bring it up again and I'll see what I can do by changing the minimum window size.
On the other hand, I'm not opposed to dividing the latter two as "Twilight Frontier" and "Miscellaneous Games" instead by moving Gouyoku Ibun to the second category. I think that's what I'll do.
I've looked over the commit, but if it's of no inconvenience, I'll be waiting for a pull request after I make the necessary UI changes alongside some bug fixes. (The main working branches are dev and dev-offline, by the way. I only merge with master after large changes such as this one.)

**Comment by HoengSaan** [comment]
Thank you for responding.
The reason why I say that PC-98 games need to be separate is that it is not that common, If that adds a lot of work to you, it is totally fine to not do that. 
The translation is pretty much done, I will do the translation again after the large changes. Also, I will try to understand what is thcrap.
And I have heard that they have a new game th18.5, hope this wouldn't make the work even harder.

**Comment by David-JonesDVN** [comment]
Hello. Sorry, I've been busy for some time. I managed to add 18.5 support and rearrange the games to fit the new categories. This is what I've come up with so far:
![newLayout](https://user-images.githubusercontent.com/12848255/188287854-9c1b3b04-42b2-418e-aa7f-9618f8a7b55a.jpg)
I opted to merge the decimal games with the mainline games to keep the number of categories constant, but I think I'll separate them again, considering how crowded the main category becomes if I don't.
I'll post a picture with the four category arrangement later, but feel free to post any other suggestions you have for the appearance, or if I should even separate the decimal games in the first place.
P.S. I just noticed that I've mixed up the placements for MoF and SA. I'll fix that for the 4-category picture.

**Comment by HoengSaan** [comment]
Yep, the decimal games are kind of cluttering. Maybe the 4-category is the better option.

**Comment by Kaethela** [comment]
I very much prefer the decimal games separated out, for what it's worth.

**Comment by David-JonesDVN** [comment]
Here's the 4-category arrangement:
![sc](https://user-images.githubusercontent.com/12848255/188320005-41510f15-c121-4b8b-bd7f-4cadf41aad19.jpg)
To be completely honest, I'm not the biggest fan of how big the launcher gets, so I did a complete redesign to see how that would turn out:
![sc2](https://user-images.githubusercontent.com/12848255/188321232-cd2536e1-81a4-4abe-808e-454e56cabc54.jpg)
Personally, I like this one better, but the decision is up to you. In case the second design is chosen, do tell me if I should keep the order from left-to-right or go with top-to-bottom order.

**Comment by Kaethela** [comment]
That second one looks perfect to me, I'd be very happy with it.

**Comment by HoengSaan** [comment]
I would say first one, who knows how far touhou can goes?
But for now second one is the best.

**Comment by David-JonesDVN** [comment]
Thank you for your patience and feedback. I've made the design changes and added the new strings to the localization files. The current builds have been attached here for testing, but I will be waiting for the translation as a pull request (on the dev and dev-offline branches) before making a full release, if that's okay. Marking this issue as closed unless there are problems with the current design.
[Touhou Launcher 1.02 Test Builds.zip](https://github.com/David-JonesDVN/Touhou-Relauncher/files/9488579/Touhou.Launcher.zip)

**Comment by HoengSaan** [comment]
I gonna try thcrap today and try to understand it.
