### ISSUE TITLE
Checkbox "custom banner" don't work

### ISSUE THREAD

**Issue by Lensrub** [David-JonesDVN/Touhou-Relauncher#3]
Hi, I found a bug: that the "Use custom banner" checkbox, after closing the window "game configuration" , does not remember value, because of this it is possible to enable custom banners only by changing the parameter in "settings.json"

**Comment by David-JonesDVN** [comment]
Thanks! I've fixed it just now but I'm not able to compile to test or release yet. Will do that as soon as I can.
