### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Lensrub** [David-JonesDVN/Touhou-Relauncher#4]
Hi, me again. Checkboxes in "random game setting" also as custom banners, do not save values.
I also discovered that "Th-hisoutensoku" and "Th-DS" are mixed up in numbers, 12.5 and 12.3 respectively.
And one more thing, is it possible to implement the same function as in the old program, which allows you to leave only a banner or the name in the "games" tab? (I mean"View mode")

**Comment by David-JonesDVN** [comment]
Hi, sorry it took this long. The first issue is intended. I never meant for it to be a saved setting, though if you do feel like it should be, do tell.
I fixed the wrong numbers and added settings for toggling the banner or text to each button's right-click menu.
There were some new strings which means they aren't translated.
[Here's the new resource file if you're interested.](https://raw.githubusercontent.com/David-JonesDVN/Touhou-Relauncher/dev/Touhou%20Launcher/Resources_ru.resx) Thanks.

**Comment by Lensrub** [comment]
[Launcher_Resources_ru.zip](https://github.com/David-JonesDVN/Touhou-Relauncher/files/3051984/Launcher_Resources_ru.zip)
Well, at least I do not use the random function, so I cant say that unsaved checkboxes bothers me much... I'm just not sure it's convenient, to re-set the values every time.

**Comment by David-JonesDVN** [comment]
I see.
I've added it regardless.
Thanks for the translation!

**Comment by Lensrub** [comment]
Some texts did not fit in size - corrected
[Resources_ru.zip](https://github.com/David-JonesDVN/Touhou-Relauncher/files/3076490/Resources_ru.zip)

**Comment by David-JonesDVN** [comment]
Thanks! Updated the text.
Also while I was at it, I made it so smaller buttons will now show the full text as their tooltip if the text doesn't fit into them. Should help with longer text.

**Comment by Lensrub** [comment]
Ok, GJ. And something else, when launch the game (using click on banner) - the launcher gives an error.

**Comment by David-JonesDVN** [comment]
I'm not getting one. What's the error? Some more details would be helpful.

**Comment by Lensrub** [comment]
When I try to start the game(beginning with TH6) by clicking on the banner, appears an error (a screenshot and details are attached), but the game still runs, only a constantly appearing error. And because of this, the "auto-close" not working.

![Screenshot_1](https://user-images.githubusercontent.com/47699634/56320442-dd611480-616c-11e9-865c-f3893cbe9240.png)
[Details.txt](https://github.com/David-JonesDVN/Touhou-Relauncher/files/3091525/Details.txt)

**Comment by David-JonesDVN** [comment]
Done. Should be fixed.

**Comment by Lensrub** [comment]
Yes, no error, ty
