### ISSUE TITLE
TH17 Doesn't Launch

### ISSUE THREAD

**Issue by Kaethela** [David-JonesDVN/Touhou-Relauncher#8]
TH17 doesn't launch when the banner button is clicked. If I right-click > configure game and launch it from one of the file paths it runs just fine, so I'm fairly certain I have everything entered correctly. I'm using the same default executable settings as the other games, and this is the only game I've found with this issue.

**Comment by David-JonesDVN** [comment]
Ah, sorry for not checking on this sooner. Should be fixed in the new build now. Thanks.
